{% set version = "2.1.2" %}

package:
  name: pygdp
  version: {{ version }}

source:
  url: https://github.com/USGS-CIDA/pyGDP/archive/v{{ version }}.tar.gz
  sha256: a0489b0fb48b1b9f81fbc6cc0518c8bcb784e69ceb696503463b3685b9dee7e2

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - owslib
    - lxml

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyGDP

about:
  home: https://github.com/USGS-CIDA/pyGDP
  license: Public Domain
  summary: 'Python interface to facilitate working with USGS-CIDA Geo Data Portal web services.'

extra:
  recipe-maintainers:
    - ocefpaf
    - ayan-usgs
    - rsignell-usgs
